version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
        update-type: "all"
    ignore:
      - dependency-name: "package-name"
    target-branch: "main"
