version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'

on:
  pull_request:
    types:
      - synchronize

jobs:
  merge-dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v0.5.0

      - name: Check for conflicts
        id: check_conflicts
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_head
          git checkout pr_head
          git merge-base --is-ancestor HEAD origin/main || echo "Conflicts detected"

      - name: Merge pull request
        run: |
          if [ -z "$(cat ${{ github.workspace }}/conflicts)" ]; then
            gh pr merge ${{ github.event.pull_request.number }} --merge --squash
          else
            echo "Conflicts detected. Manual intervention required."
          fi
