version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    working_directory: ~/pages
    executor: node/default
    steps:
     - run:
          name: Build
          command: npm run build

workflows:
  build:
    jobs:
      - build
