name: Dependabot

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependabot
        uses: dependabot/dependabot-core-action@v2.3.0
        with:
          directory: '/'
          package-ecosystem: 'npm'
          schedule: 'daily'
          open-pull-requests-limit: 5
          target-branch: 'main'
          labels: 'dependencies'
          ignore: 'package-name'
