name: Dependabot fetch metadata

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Dependabot PR
        if: steps.metadata.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dependabot/npm_and_yarn/*
          title: 'Dependabot: Update dependencies'
          body: 'This pull request updates dependencies using Dependabot.'
          labels: 'dependencies'
          base: 'main'
          draft: true
          maintainers-can-modify: true
