name: Dependabot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Dependabot
        uses: dependabot/dependabot-action@v2.7.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/workflows/dependabot.yml
