name: Build and Deploy to Vercel - myportfolio-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Log in to Vercel
        run: vercel login

      - name: Deploy to Vercel
        run: vercel --prod
